server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: orderserver
          uri: lb://ORDERSERVER
          predicates:
            - Path=/orders/**
          filters:
        #            - AddRequestHeader=first-request, first-request-header2
        #            - AddResponseHeader=first-response, first-response-header2
        - id: productserver
          uri: lb://PRODUCTSERVER
          predicates:
            - Path=/product/**
          filters:
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.example: DEBUG